name: "Домофон EVO"
version: 1.0.9
slug: doorphone
description: "Интеграция с домофоном EVO"
url: https://github.com/paulloft/ha-evo73
codenotary: info@paulloft.ru
init: false

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

ingress: true
ingress_port: 80
panel_icon: mdi:doorbell-video

map:
  - addon_config:rw
  - media:rw

options:
  phone_number: null
  webhook_url: null
  log_level: info

schema:
  phone_number: "match(7[0-9]{10})"
  webhook_url: "str?"
  log_level: list(debug|verbose|info|warnings|errors|none)
