name: Домофон Evo73
version: 1.0.0
slug: doorphone
description: Интеграция с домофоном EVO
url: https://github.com/paulloft/ha-evo73
codenotary: info@paulloft.ru
init: false

ports:
  80/tcp: 80

arch:
  - aarch64
  - amd64
  - armv7

ingress: true
ingress_port: 8099

map:
  - addon_config:rw
  - media:rw

options:
  phone_number: null
  webhook_url: null

schema:
  phone_number: "int(11)"
  webhook_url: "url?"
